#!/bin/bash
#: Title	: connectedM
#: Date		: 2017-10-13
#: Author	: "Andreas O. Bender" <andreasobender@mac.com>
#: Version	: 0.1
#: Description	: scan QR code, encode/decode ciphertext in/from QR code
#: Options	: None
#: Requires	: QR Journal, Preview


. ./functionsConnected


while :
do

printf "\n%s\n"  "1 ciphertext into QR code"
printf "%s\n"    "2 scan QR code"
printf "%s\n\n"  "3 quit"

read -p "enter option number: " choice

case $choice in
1)
  # choose ciphertext file to encode
  chooseFile

  # test whether chosen file exists
  if [ $? = 0 ]
  then
    fileToEncode=$chosenFile
    encodeFile
    # display QR code on screen
    open $fileToEncode.ps
  else 
    printf "\n%s\n\n" "file does not exist"
  fi
  ;;


2)
  scanQRcode

  # check scanned file for PGP format
  startString='\-\-\-\-\-BEGIN PGP MESSAGE-----'
  endString='\-\-\-\-\-END PGP MESSAGE-----'
 
  if [ $(grep -c "$startString" "$qrScanData") -eq 1 ] && [ $(grep -c "$endString" "$qrScanData") -eq 1 ]
  then
    # strip off formatting of scanned file
    stripFile

 pwd
 
  else
    printf "\n%s\n" "file is not PGP ciphertext"

  fi
  ;;


3)
  # quit program
  printf "\n%s\n" "bye"
  exit 0
  ;;
esac

done


